name: Build and deploy container app to Azure Web App - catchmeifyoucan001
on:
  push:
    branches:
      - master
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Log in to container registry
        uses: docker/login-action@v1
        with:
          registry: https://catchmeifyoucan.azurecr.io/
          username: ${{ secrets.AzureAppService_ContainerUsername_df8de8814754452e9fc2e072ae00d3b2 }}
          password: ${{ secrets.AzureAppService_ContainerPassword_c2e5049bd1f942a9a15b1ff6f71023d9 }}
      - name: Build and push container image to registry
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: catchmeifyoucan.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_df8de8814754452e9fc2e072ae00d3b2 }}/anamoly-detection-app:${{ github.sha }}
          file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    steps:
      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'catchmeifyoucan001'
          slot-name: 'production'
          publish-profile: ${{ secrets.AzureAppService_PublishProfile_530348ff4ec5413283828600fba7b401 }}
          images: 'catchmeifyoucan.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_df8de8814754452e9fc2e072ae00d3b2 }}/anamoly-detection-app:${{ github.sha }}'
